FROM node:18-alpine

# Set working directory
WORKDIR /app

# Add package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 5000

# Set command
CMD ["npm", "run", "dev"] 